# Generated by Django 2.0.5 on 2019-03-28 09:03

import django.contrib.sites.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSORedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sso_domain', models.CharField(max_length=100, validators=[django.contrib.sites.models._simple_domain_name_validator], verbose_name='SSO domain name')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site')),
            ],
            options={
                'verbose_name_plural': 'SSO Redirects',
                'verbose_name': 'SSO Redirect',
            },
        ),
    ]
